ALTER TABLE PROJECT ADD StartDay INT NOT NULL DEFAULT 1
ALTER TABLE PROJECT ADD EndDay INT NOT NULL DEFAULT 5
ALTER TABLE PROJECT ADD StartTime time NOT NULL DEFAULT '00:7:00'
ALTER TABLE PROJECT ADD EndTime time NOT NULL DEFAULT '00:20:00'
